### ISSUE TITLE
Display previous searches in drop down menu 

### ISSUE THREAD

**Issue by zurda** [zurda/Github-Info#15]
It would be nice if when clicking on the search field, a drop down menu with 3 of the last searches will appear.

**Comment by ksenousi** [comment]
Hi @zurda, should this be done on every visit or should it save to a cookie and have the history accessible across visits?

**Comment by zurda** [comment]
@ksenousi , it's really up to you. You can do either one :) or even both in the long run. 

Personally, the way I imagined it is displaying the 3 or even 5 recent valid searches. 

An example use would be: 

1. I searched for @ksenousi, and then moved on to view another profile 
2. I then changed my mind and wanted to go back to your profile

So it would be nice it it would appear in the bottom to save the user clicking the entire username all over, OR perhaps we can even save all the valid searches, and show previous searches as autocorrect? So after I click the `s` -> your profile would be suggested in a dropdown menu. 

Does this make sense?

The second option you suggested is also an improvement, I admit, I hadn't thought of that one, so feel free to choose either one :) You can also open a different issue for the second option for clarity, if you think it's best.

**Comment by zurda** [comment]
Another option is to have a drop down menu that shows usernames that start with these letters :) You can choose either of these that looks the most appealing to work on!
