### ISSUE TITLE
Fix display for mobile 

### ISSUE THREAD

**Issue by zurda** [zurda/Github-Info#27]
Input field should appear beneath app name

**Comment by mrassili** [comment]
I'll be working on this, do you think CSS Grid is better suited solution ?

**Comment by zurda** [comment]
Tbh, the goal was to style this like Github, but Github isn't optimised for mobile neither so I'm not sure what the best approach is here. 

- I think having a higher header, with the input field under the app name should look better, but feel free to try a different approach 
- If you choose the make the header twice as high, I would center the logo and app name as well as the input field 
- Also, probably the button isn't needed for mobile, since we use the keyboard

**Comment by zurda** [comment]
@mrassili I also just shortened the app name to `Github display` :) so that might help. If it's not too late, please use the most recent version when you make your changes
