### ISSUE TITLE
Improve transition from one user info to the other 

### ISSUE THREAD

**Issue by zurda** [zurda/Github-Info#28]
At the moment, the image and content just changes instantly when the new data arrives. There should be a nice transition (fade in/out?) that will make it clearer that the page has been changed. 

-> A welcomed side affect of this might be that the new image + new text would look like they appear simultaneously (at the moment, they aren't).

**Comment by ksenousi** [comment]
Hi,
I would like to work on this @zurda.

**Comment by zurda** [comment]
Sure thing, @ksenousi !
