### ISSUE TITLE
If the request returns 404 -> inform the user `user not found`

### ISSUE THREAD

**Issue by zurda** [zurda/Github-Info#31]

**Comment by ksenousi** [comment]
Hi, I am new to open source and am interested in helping. What are exactly are you looking for? Is there a way I could help?

**Comment by ksenousi** [comment]
I was thinking maybe creating flash messages for both invalid username or username not found. Something like the image I attached
![screen shot 2018-08-27 at 20 02 24](https://user-images.githubusercontent.com/22755568/44679972-5b34ac00-aa34-11e8-8b10-1c62add058f9.png)

**Comment by zurda** [comment]
Having a similar style for both `user not found` and `invalid username` is a great idea. Perhaps even consider adding the `loading` message in there? (but with green background, rather than red, which indicates an error). Sort of a status display right under the header.

**Comment by ksenousi** [comment]
Awesome. I'll work on that then. 
Quick question: Could you explain what the auth.js file is?
