### ISSUE TITLE
Display user info in an order similar to a github page 

### ISSUE THREAD

**Issue by zurda** [zurda/Github-Info#32]
This refers to the order of the fields, rather than their css style. 

In a github profile page, the info is displayed like so: 

![screen shot 2018-08-27 at 15 04 02](https://user-images.githubusercontent.com/16784959/44664222-84d8dd80-aa0a-11e8-8b93-7e8cd3aed4e5.png)

So the order is: 

- Avatar 
- name 
- username
- bio 
- location 

We should display our fields in the same order. This way, we might be able to remove the `name:`, `bio:`, `username:` labels before the values.

**Comment by Wgil** [comment]
Hello, I'll be working on this. :)

**Comment by zurda** [comment]
Awesome, @Wgil ! I appreciate it!
Don't forget to add your name to `CONTRIBUTING.md` before creating the PR. 
Also, feel free to suggest other improvements
