### ISSUE TITLE
Format large numbers to display with comma 

### ISSUE THREAD

**Issue by zurda** [zurda/Github-Info#39]
This is the current look: 

![screen shot 2018-08-28 at 12 59 24](https://user-images.githubusercontent.com/16784959/44721572-430b6e00-aac2-11e8-8710-daf076b531d6.png)

We should format int's to display with a comma, like so: `103,826 `, `16,391 `, etc

**Comment by Wgil** [comment]
We could use this one https://github.com/yahoo/react-intl/wiki/Components#formattednumber
