### ISSUE TITLE
Add links to most foked and most starred repo 

### ISSUE THREAD

**Issue by zurda** [zurda/Github-Info#40]
The bottom two items in this image should also have a link to the repo in hand: 

![screen shot 2018-08-28 at 15 06 39](https://user-images.githubusercontent.com/16784959/44728292-fdf03780-aad3-11e8-8bcb-357d5cccb190.png)

**Comment by Wgil** [comment]
Helloo,

Let me check this out

**Comment by zurda** [comment]
Sure thing, @Wgil !
