### ISSUE TITLE
Add feedback when the input field has a username that is currently displayed 

### ISSUE THREAD

**Issue by zurda** [zurda/Github-Info#54]
When the input field is, for example, `getify` (as in when the page loads), we can click the button with no indication that `getify`'s info is already displayed. We need to add feedback to let the user know that the card below is the card of the user in the input field. 

The feedback can be making the card edges darker for a second, or some other sort of flashing of the card.

**Comment by ksenousi** [comment]
I'll work on this one @zurda. :)
