### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by ksenousi** [zurda/Github-Info#70]
Adding a license would make it clear what others are allowed to do with your code.

Here's a link to an explanation:
https://help.github.com/articles/licensing-a-repository/

and this link guides you to which license to pick:
https://choosealicense.com

**Comment by zurda** [comment]
Thanks for suggesting this issue @ksenousi . I think the MIT is a standard, so who ever picks this up - I'm leaning towards that but I'm open to suggestions of course
