### ISSUE TITLE
Display contributors avatar and username 

### ISSUE THREAD

**Issue by zurda** [zurda/Github-Info#80]
Would be great to display the contributors avatar and username in `CONTRIBUTING.md` 
I'm pretty sure it should be available on the API so marking this as a good first issue (but happy to remove that if it turns out to be more of an effort)

**Comment by zh-betina** [comment]
Hi, @zurda May I have a try? 😁

**Comment by zurda** [comment]
Hi @zh-betina , of course, thanks! Thanks for offering. Hopefully this is indeed in the API and something that's easy to get.

**Comment by zh-betina** [comment]
@zurda Thanks for assigning it to me! I've already found a solution - I'll try it out this evening.😃

**Comment by zh-betina** [comment]
@zurda I like this solution but I think I need you to choose one: <br>
1.) [Option with CLI](https://allcontributors.org/docs/en/cli/installation) <br>
2.) [Option with Bot](https://allcontributors.org/docs/en/bot/installation).

If you choose the second one, I think you still need to do the first step of installing the bot and make it access your repository.
I can do the configuration part.
For the first option, the owner (probably) doesn't need to do anything.

**Comment by zurda** [comment]
Hi @zh-betina , thanks for the update. 
So, if I understand correctly in both cases there's a bit that I'll have to do? I wouldn't want to block you. I hope to get to this later today or tomorrow, but I might only get a chance to sort this on the weekend. 
I guess I'm saying, I'm happy to go with either, but just a heads up - it might take me a few days to set up, so I hope I'm not blocking you 🌹

**Comment by zh-betina** [comment]
@zurda You're welcome! 
I think the CLI option doesn't need anything from you - I just wanted to make sure which option is more preferable for you. Anyway, I can do the CLI-thing and if you wish it to be more automated in the future (even the near one 😃), I'll be more than happy to help with that again.
It's really as you wish, don't worry about blocking me - I'm a patient girl 😁

**Comment by zurda** [comment]
thanks for explaining. I've just added the bot to this repo - I hope this will suffice, let me know if there's anything else I can do

**Comment by zh-betina** [comment]
@zurda Hi, I added more detailed info in my pull request info but once the PR is approved and merged, we can try it out by "calling out" the bot in this issue thread here to add the contributors you already got in your CONTRIBUTING.md file. We try with one contributor first, so that the bot generates the configuration file, that needs to be edited before merging (I explained that in my PR info). After the first contributor update, it'll be easier 😁 

Please, let me know in case there are issues. I played a lot with the thing on the forked repo.

**Comment by zurda** [comment]
Hi @zh-betina , your PR looks good, happy to try it. Could you create a PR on this repo so we can merge it and see it live?

**Comment by zurda** [comment]
Looking good, thanks @zh-betina !
